name: Auto Release
permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  publish-release:
    name: "Publish Release"
    runs-on: ubuntu-latest
    steps:
      # 获取 Tag 名称
      - name: Get Tag Name
        run : |
          echo "Ref Name: $GITHUB_REF"
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      # 发布 Release
      - name: Publish Release
        uses: "softprops/action-gh-release@v1"
        with:
          name: "日神杀武将包 ${{ env.TAG_NAME }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          generate_release_notes: true

      # 华为云认证
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
            access_key_id: ${{ secrets.ACCESSKEY }} 
            secret_access_key: ${{ secrets.SECRETACCESSKEY }}
            # 华南-广州
            region: 'cn-south-1'

      # 从华为云 OBS 下载基础文件
      - name: Download File from Huawei Cloud OBS
        uses: huaweicloud/obs-helper@v1.0.0
        with:
          bucket_name: 'obs-github'
          local_file_path: '${{ runner.temp }}/'
          obs_file_path: 'qsgs-pure.zip'
          operation_type: 'download'

      # 安装 Zip 扩展
      - name: Install zip
        uses: montudor/action-zip@v1

      # 解压基础文件
      - name: Unzip the Basic Files
        run: unzip -qq ${{ runner.temp }}/qsgs-pure.zip -d ${{ runner.temp }}/QSGS-v2-Lua-${{ env.TAG_NAME }}

      # 检出分支
      - name: Checkout Branch
        uses: actions/checkout@v3

      # 复制当前分支文件到临时文件夹
      - name: Copy Branch Files
        run: cp -r ${{ github.workspace }}/* ${{ runner.temp }}/QSGS-v2-Lua-${{ env.TAG_NAME }}

      # 移除不需要的文件
      - name: Remove Unnecessary Files
        run: |
          rm ${{ runner.temp }}/QSGS-v2-Lua-${{ env.TAG_NAME }}/*.md
          rm -rf ${{ runner.temp }}/QSGS-v2-Lua-${{ env.TAG_NAME }}/.[A-Za-z0-9]*

      # 打包成 zip
      - name: Archive Files
        uses: thedoctor0/zip-release@0.7.1
        with:
          directory: ${{ runner.temp }}
          type: 'zip'
          filename: 'QSGS-v2-Lua-${{ env.TAG_NAME }}.zip'
          path: ./QSGS-v2-Lua-${{ env.TAG_NAME }}

      # 上传压缩包
      - name: Upload Archive
        uses: svenstaro/upload-release-action@2.5.0
        with:
          file: "${{ runner.temp }}/QSGS-v2-Lua-${{ env.TAG_NAME }}.zip"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: "QSGS-v2-Lua-${{ env.TAG_NAME }}.zip"
