name: Auto Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "ci/*"

jobs:
  # Just Publish the Release Information
  # publish-release:
  #   name: "Publish Release"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Tag Name
  #       run : |
  #         echo "Ref Name: $GITHUB_REF"
  #         echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

  #     - name: Publish Release
  #       uses: "marvinpinto/action-automatic-releases@latest"
  #       with:
  #         title: "日神杀武将包 ${{ env.TAG_NAME }}"
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         prerelease: false
  #         draft: false

  directory-echo:
    name: "Directory Echo Test"
    runs-on: ubuntu-latest
    steps:
      # ${{ github.workspace }}为action运行时的工作目录
      - name: Echo Workspace of Action
        run: echo ${{ github.workspace }}

      # ${{ runner.temp }}为运行器临时目录的路径
      - name: Echo Temporary Directory on the Runner
        run: echo ${{ runner.temp }}
