name: LuaCheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lua-Format-Check:
    name: Lua Specification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Clean LuaRocks Cache
        run: |
          echo "Cleaning the Lua Rocks Cache..."
          echo "Check If Cache Exists..."
          if [ -d "~/.cache/luarocks" ];then
              echo "Cache Exists! Cleaning..."
              rm -rf ~/.cache/luarocks
            else
              echo "No need to Clean Cache!"
          fi
      - name: Lua Lint
        uses: GoatG33k/fivem-lua-lint-action@v1
        with:
          capture: "junit.xml"
          args: "-d -t --ignore 112 113 143 212 --formatter JUnit"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.6.2
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: true
          check_name: JUnit Report
