name: LuaCheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lua-Format-Check:
    name: Lua Specification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Lua Lint
        uses: GoatG33k/fivem-lua-lint-action@v1
        with:
          capture: "junit.xml"
          args: "-d -t --ignore 112 113 143 212 --formatter JUnit"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2.5.1
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: true
          check_name: JUnit Report

  Email-Notification:
    name: "Email Notification"
    runs-on: ubuntu-latest
    steps:
      - name: "Send Email"
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtpdm.aliyun.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: MR Notification
          # Required recipients' addresses:
          to: 954732822@qq.com
          # Required sender full name (address can be skipped):
          from: Rinkosanvsky
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          body: ${{github.actor}} 发起 MR。请尽快 CR
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
