name: LuaCheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lua-Format-Check:
    name: Lua Specification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Lua Lint
        uses: lunarmodules/luacheck@v1.1.2
        with:
          args: ". -d -t --ignore 112 113 143 212 --formatter JUnit"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3.6.2
        if: always()
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: true
          check_name: JUnit Report
