name: LuaCheck
permissions:
  contents: read
  checks: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lua-Format-Check:
    name: Lua Specification Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Lua Lint
        uses: lunarmodules/luacheck@v1.2.0
        with:
          args: "-d -t --ignore 112 113 143 212 --max-line-length 130 --formatter JUnit . >> ./junit.xml"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "**/junit.xml"
          fail_on_failure: true
          check_name: LuaCheck JUnit Report
