name: LuaCheckTest

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
    - /**
  pull_request:
    branches: [ master ]

jobs:
  lua-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: nebularg/actions-luacheck@v1
      with:
        args: -o 011
