name: 'Pull Request Specification Check'

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited
    branches:
      - master

jobs:
  Pull-Request-Title-Check:
    name: 'Pull Request Title Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull Request Title Check'
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Pull-Request-Label-Check:
    name: 'Pull Request Label Check'
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: invalid,wontfix,duplicate,question
          any_of: documentation,enhancement,bug,general fix,github issue,structure
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  Pull-Request-Issue-Check:
    name: 'Pull Request Linked Issue Check'
    runs-on: ubuntu-latest
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Email-Notification:
    name: "Email Notification"
    uses: dawidd6/action-send-mail@v3
    needs: [Pull-Request-Title-Check, Pull-Request-Label-Check, Pull-Request-Issue-Check]
    with:
      # Required mail server address:
      server_address: smtpdm.aliyun.com
      # Required mail server port:
      server_port: 465
      # Optional (recommended): mail server username:
      username: ${{secrets.MAIL_USERNAME}}
      # Optional (recommended) mail server password:
      password: ${{secrets.MAIL_PASSWORD}}
      # Required mail subject:
      subject: MR Notification
      # Required recipients' addresses:
      to: 954732822@qq.com
      # Required sender full name (address can be skipped):
      from: Rinkosanvsky
      # Optional whether this connection use TLS (default is true if server_port is 465)
      secure: true
      # Optional plain body:
      body: ${{github.actor}} initiates a MR progress. Please CR as soon as possible
      # Optional unsigned/invalid certificates allowance:
      ignore_cert: true
      # Optional converting Markdown to HTML (set content_type to text/html too):
      convert_markdown: true
      # Optional priority: 'high', 'normal' (default) or 'low'
      priority: high
