name: 'Pull Request Specification Check'

on: 
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

jobs:
  Pull-Request-Title-Check:
    name: 'Pull Request Title Check'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull Request Title Check'
        uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Pull-Request-Label-Check:
    name: 'Pull Request Label Check'
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          none_of: invalid,wontfix,duplicate,question
          any_of: documentation,enhancement,bug,fix,ci
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  Pull-Request-Issue-Check:
    name: 'Pull Request Linked Issue Check'
    runs-on: ubuntu-latest
    steps:
    - name: Verify Linked Issue
      uses: hattan/verify-linked-issue-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
